### ISSUE TITLE
MoNA Offline and some local databases not working

### ISSUE THREAD

**Issue by schymane** [ipb-halle/MetFragRelaunched#112]
As posted via MetFrag feedback, now moving to issue as requested by @sneumann, so far we've noticed: 
- MoNA Offline Exact scores = 0, even for stock standard spectra in MassBank that always work
- Local versions of YMDB and HMDB are not working (error fetching candidates)
- Local versions of PubChemLite for Exposomics seem to work
- Server version of HMDB (and others) seem to work

**Comment by sneumann** [comment]
I can confirm the local HMDB and YMDB, logs show
```
10:04:25.658 ERROR de.ipbhalle.metfraglib.database.LocalCSVDatabase - Error: No Identifier column defined.
```
and indeed the following local databases are empty, so likely a container build issue:
```
-rw-r--r-- 1 root root         0 Jan 30 09:41 CompTox_07March19_WWMetaData.csv
-rw-r--r-- 1 root root         0 Jan 30 09:43 Zebrafish_13Nov2019_Beta.csv
-rw-r--r-- 1 root root         0 Jan 30 09:45 EColiMDB_11Nov2019.csv
-rw-r--r-- 1 root root         0 Jan 30 09:47 YMDB2_17Sept2019.csv
-rw-r--r-- 1 root root         0 Jan 30 09:49 WormJam_10Sept19.csv
-rw-r--r-- 1 root root         0 Jan 30 09:51 HMDB4_23Aug19.csv
```

**Comment by sneumann** [comment]
The spectral-library failure is a local deployment issue.  Since last year there is the new option to add custom spectral libraries into a directory. If that is empty, none is used. If there is no directory, the default embedded MoNA is used. 
Currently, I have an empty directory there. Need to change that.

**Comment by sneumann** [comment]
The Spectral library issue was fixed in default helm installations in https://github.com/ipb-halle/ipb-charts-public/commit/f1ad00f0e5f87cd12115bc0175fa15429a8b80bd

**Comment by schymane** [comment]
We can confirm that the patches seem to be working well on Beta ;-)

**Comment by schymane** [comment]
@sneumann has confirmed there were multiple MetFragBeta instances with different versions (which explains our observations), fixing this is WiP ... (thanks @sneumann ;-) )

**Comment by schymane** [comment]
We still have some versions of MetFragBeta giving `Error fetching candidates` from YMDB for students ... but both Beta and the main website seem to work fine for me so far (at least wrt YMDB and MoNA)! ;-) 
(how does it know who is the teacher?! ;-) )

**Comment by schymane** [comment]
Seems everything worked like a charm today, so closing this now - thanks for your help updating things this week @sneumann  👍
